//
//  SwiftUIView.swift
//  UltraSolem_final
//
//  Created by Teck Hao Tea on 31/10/2022.
//

import SwiftUI

struct Astre: Identifiable {

var id = UUID()
var name: String
var chapitre : String // Nom de la planète de provenance
var nature: String //(Etoile, Planète, Satellite)
var age: Double // exprimé en années
var dateDecouverte: String //???
var sizeRayon: Double
var sizeCirconference: Double //(à voir si on fait le calcul à partir du rayon)
var distanceTerre: Double // (Unité à définir ou adapter en fonction de la distance)
var composition1: String
var composition1Pourcent: Double
var composition2: String
var composition2Pourcent: Double
var composition3: String
var composition3Pourcent: Double
var satellites: String
var temperature: Double // temp. moyenne en celcius à la surface
var imagePrincipale: String // Objet Céleste HD détourée vue InfoAstreView
var imageSecondaire: String // Objet Céleste HD vue InfoAstreView
var imageBigTile: String // Objet Céleste HD fond noir vue JournalView BigTile
var imageLittleTile: String // Objet Céleste HD fond noir vue JournalView LittleTile
var texteDescription1: String // Définir nb de caractère max
var texteDescription2: String // Définir nb de caractère max
var texteFact1: String // Définir nb de caractère max
var texteFact2: String // Définir nb de caractère max
var texteNews1: String // Définir nb de caractère max
var texteNews2: String // Définir nb de caractère max
var texteCourt: String // Définir nb de caractère max + Texte affiché sous le nom de la planète sur les tuiles du journal
    var index : Int

}

var astres = [
Astre(name: "Unknown", chapitre: "tous", nature: "tous", age: 0, dateDecouverte: "", sizeRayon: 0, sizeCirconference: 0, distanceTerre: 0, composition1: "", composition1Pourcent: 0, composition2: "", composition2Pourcent: 0, composition3: "", composition3Pourcent: 0, satellites: "", temperature: 0, imagePrincipale: "", imageSecondaire: "", imageBigTile: "", imageLittleTile: "", texteDescription1: "", texteDescription2: "", texteFact1: "", texteFact2: "", texteNews1: "", texteNews2: "", texteCourt: "", index: 0),

Astre(name: "Soleil",
                    chapitre : "La ceinture d'astéroïdes",
                    nature: "Etoile",
                    age: 4603000000,
                    dateDecouverte: "24 Octobre 2022",
                    sizeRayon: 696340,
                    sizeCirconference: 4379000,
                    distanceTerre: 149597870.7,
                    composition1: "Hydrogène",
                    composition1Pourcent: 0.74,
                    composition2: "Hélium",
                    composition2Pourcent: 0.25,
                    composition3: "Autre",
                    composition3Pourcent: 0.01,
                    satellites: "Aucun",
                    temperature: 5900,
                    imagePrincipale: "Soleil.image1",
                    imageSecondaire: "Soleil.image2",
                    imageBigTile: "Soleil.bigTile",
                    imageLittleTile: "Soleil.littleTile",
                    texteDescription1: "Le Soleil est l’étoile du Système solaire. Dans la classification astronomique, c’est une étoile de type naine jaune d'une masse d'environ 1,989 1 × 1030 kg, composée d’hydrogène (74 % de la masse ou 92 % du volume) et d’hélium (25 % de la masse ou 8 % du volume). Le Soleil fait partie de la galaxie appelée la Voie lactée et se situe à environ 8 kpc (∼26 100 a.l.) du centre galactique, dans le bras d'Orion. Le Soleil orbite autour du centre galactique en une année galactique de 225 à 250 millions d'années. Autour de lui gravitent la Terre (à la vitesse de 30 km/s), sept autres planètes, au moins cinq planètes naines, de très nombreux astéroïdes et comètes et une bande de poussière. Le Soleil représente à lui seul environ 99,854 % de la masse du système planétaire ainsi constitué, Jupiter représentant plus des deux tiers du reste.",
                    texteDescription2: "TextDescription2 Lorem ipsum",
                    texteFact1: "texteFact1 Lorem ipsum",
                    texteFact2: "texteFact2 Lorem ipsum",
                    texteNews1: "texteNews1 Lorem ipsum",
                    texteNews2: "texteNews2 Lorem ipsum",
                    texteCourt: "Notre étoile",
                                        index: 1),

//01
Astre(name: "Mercure",
                    chapitre : "Le cairn",
                    nature: "Planète",
                    age: 4603000000,
                    dateDecouverte: "24 Octobre 2022",
                    sizeRayon: 696340,
                    sizeCirconference: 4379000,
                    distanceTerre: 149597870.7,
                    composition1: "Hydrogène",
                    composition1Pourcent: 0.74,
                    composition2: "Hélium",
                    composition2Pourcent: 0.25,
                    composition3: "Autre",
                    composition3Pourcent: 0.01,
                    satellites: "Aucun",
                    temperature: 5900,
                    imagePrincipale: "Mercure.image1",
                    imageSecondaire: "Mercure.image2",
                    imageBigTile: "Mercure.bigTile",
                    imageLittleTile: " Mercure.littleTile",
                    texteDescription1: "Mercure est la planète la plus proche du Soleil et la moins massive du Sytème solaire.",
                    texteDescription2: "TextDescription2 Lorem ipsum",
                    texteFact1: "texteFact1 Lorem ipsum",
                    texteFact2: "texteFact2 Lorem ipsum",
                    texteNews1: "texteNews1 Lorem ipsum",
                    texteNews2: "texteNews2 Lorem ipsum",
                    texteCourt: "Voisine du soleil",
                                        index: 2),

Astre(name: "Venus",
                    chapitre : "Le cairn",
                    nature: "Planète",
                    age: 4603000000,
                    dateDecouverte: "24 Octobre 2022",
                    sizeRayon: 696340,
                    sizeCirconference: 4379000,
                    distanceTerre: 149597870.7,
                    composition1: "Hydrogène",
                    composition1Pourcent: 0.74,
                    composition2: "Hélium",
                    composition2Pourcent: 0.25,
                    composition3: "Autre",
                    composition3Pourcent: 0.01,
                    satellites: "Aucun",
                    temperature: 5900,
                    imagePrincipale: "Venus.image1",
                    imageSecondaire: "Venus.image2",
                    imageBigTile: "Venus.bigTile",
                    imageLittleTile: "Venus.littleTile",
                    texteDescription1: "Vénus est la deuxième planète du Système solaire par ordre d'éloignement au Soleil, et la sixième plus grosse aussi bien par la masse que le diamètre. Elle doit son nom à la déesse romaine de l'amour.Vénus orbite autour du Soleil tous les 224,7 jours terrestres. Avec une période de rotation de 243 jours terrestres, il lui faut plus de temps pour tourner autour de son axe que toute autre planète du Système solaire. Comme Uranus, elle possède une rotation rétrograde et tourne dans le sens opposé à celui des autres planètes : le soleil s'y lève à l'ouest et se couche à l'est. Vénus possède l'orbite la plus circulaire des planètes du Système solaire avec une excentricité orbitale presque nulle et, du fait de sa lente rotation, est quasiment sphérique (aplatissement considéré comme nul). Elle ne possède pas de satellite naturel.",
                    texteDescription2: "TextDescription2 Lorem ipsum",
                    texteFact1: "texteFact1 Lorem ipsum",
                    texteFact2: "texteFact2 Lorem ipsum",
                    texteNews1: "texteNews1 Lorem ipsum",
                    texteNews2: "texteNews2 Lorem ipsum",
                    texteCourt: "Déesse tellurique",
                                        index: 3),

Astre(name: "Terre",
                chapitre : "Le sydrome de Kessler",
                nature: "Planète",
                age: 4543000000,
                dateDecouverte: "01 Aout 2022",
                sizeRayon: 6371,
                sizeCirconference: 40075,
                distanceTerre: 0,
                composition1: "Oxygène",
                composition1Pourcent: 0.47,
                composition2: "Silicium",
                composition2Pourcent: 0.28,
                composition3: "Autre",
                composition3Pourcent: 0.25,
                satellites: "Lune",
                temperature: 13.7,
                imagePrincipale: "Terre.image1",
                imageSecondaire: "Terre.image2",
                imageBigTile: "Terre.bigTile",
                imageLittleTile: "Terre.littleTile",
                texteDescription1: "La Terre est la troisième planète par ordre d'éloignement au Soleil et la cinquième plus grande du Système solaire aussi bien par la masse que par le diamètre. Par ailleurs, elle est le seul objet céleste connu pour abriter la vie. Elle orbite autour du Soleil en 365,256 jours solaires — une année sidérale — et réalise une rotation sur elle-même relativement au Soleil en un jour sidéral (environ 23 h 56 min 4 s), soit un peu moins que son jour solaire de 24 h du fait de ce déplacement autour du Soleila. L'axe de rotation de la Terre possède une inclinaison de 23°, ce qui cause l'apparition des saisons.",
                texteDescription2: "TextDescription2 Lorem ipsum",
                texteFact1: "texteFact1 Lorem ipsum",
                texteFact2: "texteFact2 Lorem ipsum",
                texteNews1: "texteNews1 Lorem ipsum",
                texteNews2: "texteNews2 Lorem ipsum",
                texteCourt: "Le vaisseau amiral",
                                        index: 4),

Astre(name: "Mars",
                chapitre : "Assistance gravitationnelle",
                nature: "Planète",
                age: 4603000000,
                dateDecouverte: "26 Octobre 2022",
                sizeRayon: 3389.5,
                sizeCirconference: 21344,
                distanceTerre: 78000000,
                composition1: "Dioxyde de Carbone",
                composition1Pourcent: 0.96,
                composition2: "Argon",
                composition2Pourcent: 0.02,
                composition3: "Autre",
                composition3Pourcent: 0.02,
                satellites: "Phobos, Déimos",
                temperature: -63,
                imagePrincipale: "Mars.image1",
                imageSecondaire: "Mars.image2",
                imageBigTile: "Mars.bigTile",
                imageLittleTile: "Mars.littleTile",
                texteDescription1: "Mars est la 4ème planète du système solaire. Voisine de la Terre, elle comme elle des journées d’environ 24 heures (et 40 minutes) et 4 saisons. Depuis les années 70, elle est le sujet de nombreuses missions spatiales.",
                texteDescription2: "TextDescription2 Lorem ipsum",
                texteFact1: "texteFact1 Lorem ipsum",
                texteFact2: "texteFact2 Lorem ipsum",
                texteNews1: "texteNews1 Lorem ipsum",
                texteNews2: "texteNews2 Lorem ipsum",
                texteCourt: "La planète rouge",
                                        index: 5),

Astre(name: "Jupiter",
                chapitre : "L'oeil de Ganymède",
                nature: "Planète",
                age: 4603000000,
                dateDecouverte: "21 Octobre 2022",
                sizeRayon: 69911,
                sizeCirconference: 439264,
                distanceTerre: 628730000,
                composition1: "Hydrogène",
                composition1Pourcent: 0.93,
                composition2: "Hélium",
                composition2Pourcent: 0.7,
                composition3: "Autre",
                composition3Pourcent: 0,
                satellites: "Europe, Io, Ganymède, Callisto...",
                temperature: -123,
                imagePrincipale: "jupiter.image1",
                imageSecondaire: "jupiter.image2",
                imageBigTile: "jupiter.bigTile",
                imageLittleTile: "jupiter.littleTile",
                texteDescription1: "Jupiter est la 5ème planète du système solaire et est l’une des 4 planètes géantes gazeuses, étant principalement composée de gaz et dépourvue de réelle surface.",
                texteDescription2: "TextDescription2 Lorem ipsum",
                texteFact1: "texteFact1 Lorem ipsum",
                texteFact2: "texteFact2 Lorem ipsum",
                texteNews1: "texteNews1 Lorem ipsum",
                texteNews2: "texteNews2 Lorem ipsum",
                texteCourt: "La plus grande planète du système",
                                        index: 6),

Astre(name: "Saturne",
                chapitre : "L'ombre de Titan",
                nature: "Planète",
                age: 4503000000,
                dateDecouverte: "26 Octobre 2022",
                sizeRayon: 58232,
                sizeCirconference: 378675,
                distanceTerre: 1426800000,
                composition1: "Hydrogène",
                composition1Pourcent: 0.96,
                composition2: "Hélium",
                composition2Pourcent: 0.3,
                composition3: "Autre",
                composition3Pourcent: 0.01,
                satellites: "Aucun",
                temperature: -140,
                imagePrincipale: "Saturne.image1",
                imageSecondaire: "Saturne.image2",
                imageBigTile: "Saturne.bigTile",
                imageLittleTile: "Saturne.littleTile",
                texteDescription1: "Saturne est la sixième planète du Système solaire par ordre d'éloignement au Soleil, et la deuxième plus grande par la taille et la masse après Jupiter, qui est comme elle une planète géante gazeuse. Son rayon moyen de 58 232 km est environ neuf fois et demi celui de la Terre et sa masse de 568,46 × 1024 kg est 95 fois plus grande. Orbitant en moyenne à environ 1,4 milliard de kilomètres du Soleil (9,5 unités astronomiques), sa période de révolution vaut un peu moins de 30 années tandis que sa période de rotation est estimée à 10 h 33 min.",
                texteDescription2: "TextDescription2 Lorem ipsum",
                texteFact1: "texteFact1 Lorem ipsum",
                texteFact2: "texteFact2 Lorem ipsum",
                texteNews1: "texteNews1 Lorem ipsum",
                texteNews2: "texteNews2 Lorem ipsum",
                texteCourt: "La sixème planète",
                                        index: 7),

Astre(name: "Uranus",
                chapitre : "La suite... plus tard.",
                nature: "Planète",
                age: 4503000000,
                dateDecouverte: "26 Octobre 2022",
                sizeRayon: 58232,
                sizeCirconference: 378675,
                distanceTerre: 1426800000,
                composition1: "Hydrogène",
                composition1Pourcent: 0.96,
                composition2: "Hélium",
                composition2Pourcent: 0.3,
                composition3: "Autre",
                composition3Pourcent: 0.01,
                satellites: "Aucun",
                temperature: -140,
                imagePrincipale: "Uranus.image1",
                imageSecondaire: "Uranus.image2",
                imageBigTile: "Uranus.bigTile",
                imageLittleTile: "Uranus.littleTile",
                texteDescription1: "Uranus est la septième planète du Système solaire par ordre d'éloignement du Soleil. Elle orbite autour de celui-ci à une distance d'environ 19,2 unités astronomiques (2,87 milliards de kilomètres), avec une période de révolution de 84,05 années terrestres. Il s'agit de la quatrième planète la plus massive du Système solaire et de la troisième plus grande par la taille.",
                texteDescription2: "TextDescription2 Lorem ipsum",
                texteFact1: "texteFact1 Lorem ipsum",
                texteFact2: "texteFact2 Lorem ipsum",
                texteNews1: "texteNews1 Lorem ipsum",
                texteNews2: "texteNews2 Lorem ipsum",
                texteCourt: "La spetième planète",
                                        index: 8),


Astre(name: "Neptune",
                chapitre : "La suite... plus tard.",
                nature: "Planète",
                age: 4503000000,
                dateDecouverte: "21 Octobre 2022",
                sizeRayon: 24622,
                sizeCirconference: 155600,
                distanceTerre: 4300000000,
                composition1: "Eau",
                composition1Pourcent: 0,
                composition2: "Amoniac",
                composition2Pourcent: 0,
                composition3: "Méthane",
                composition3Pourcent: 0,
                satellites: "Miranda, Titania, Obéron, Ariel...",
                temperature: -123,
                imagePrincipale: "Neptune.image1",
                imageSecondaire: "Neptune.image2",
                imageBigTile: "Neptune.bigTile",
                imageLittleTile: "Neptune.littleTile",
                texteDescription1: "Neptune est la 8ème planète du Système solaire. Elle est désignée comme une géante des glaces. Cette planète n’a pas un corps solide et est survolée par les vents les plus violents du Système solaire (allant jusqu’à 2100 km/h !).",
                texteDescription2: "TextDescription2 Lorem ipsum",
                texteFact1: "texteFact1 Lorem ipsum",
                texteFact2: "texteFact2 Lorem ipsum",
                texteNews1: "texteNews1 Lorem ipsum",
                texteNews2: "texteNews2 Lorem ipsum",
                texteCourt: "La planète lointaine de notre système",
      index:9),

//09
Astre(name: "ISS",
                chapitre : "Les signaux",
                nature: "Satellite",
                age: 24,
                dateDecouverte: "20 Octobre 2022",
                sizeRayon: 110,
                sizeCirconference: 0,
                distanceTerre: 408,
                composition1: "N/A",
                composition1Pourcent: 0,
                composition2: "N/A",
                composition2Pourcent: 0,
                composition3: "N/A",
                composition3Pourcent: 0,
                satellites: "Aucun",
                temperature: 18,
                imagePrincipale: "ISS.image1",
                imageSecondaire: "ISS.image2",
                imageBigTile: "ISS.bigTile",
                imageLittleTile: "ISS.littleTile",
                texteDescription1: "La Station Spatiale Internationale sert de base pour préparer les voyages spatiaux, tester les effets de l’espace sur la physiologie humaine et éprouver la résistance de nouveaux matériaux.",
                texteDescription2: "TextDescription2 Lorem ipsum",
                texteFact1: "texteFact1 Lorem ipsum",
                texteFact2: "texteFact2 Lorem ipsum",
                texteNews1: "texteNews1 Lorem ipsum",
                texteNews2: "texteNews2 Lorem ipsum",
                texteCourt: "Station Spatiale Internationale",
                                        index: 10),
//010
Astre(name: "Ceinture de débris",
                chapitre : "Les signaux",
                nature: "Satellite",
                age: 24,
                dateDecouverte: "20 Octobre 2022",
                sizeRayon: 110,
                sizeCirconference: 0,
                distanceTerre: 408,
                composition1: "N/A",
                composition1Pourcent: 0,
                composition2: "N/A",
                composition2Pourcent: 0,
                composition3: "N/A",
                composition3Pourcent: 0,
                satellites: "Aucun",
                temperature: 18,
                imagePrincipale: "ISS.image1",
                imageSecondaire: "ISS.image2",
                imageBigTile: "Ceinture de débris.bigTile",
                imageLittleTile: "Ceinture de débris.littleTile",
                texteDescription1: "Une ceinture de débris est un disque circumstellaire formé de poussière et d’astéroïdes de toutes tailles.",
                texteDescription2: "TextDescription2 Lorem ipsum",
                texteFact1: "texteFact1 Lorem ipsum",
                texteFact2: "texteFact2 Lorem ipsum",
                texteNews1: "texteNews1 Lorem ipsum",
                texteNews2: "texteNews2 Lorem ipsum",
                texteCourt: "Le disque de débris",
                                        index: 11),
//011
Astre(name: "Lune",
                chapitre : "Assistance gravitationnelle",
                nature: "Satellite",
                age: 4530000000,
                dateDecouverte: "17 Octobre 2022",
                sizeRayon: 1737.4,
                sizeCirconference: 10921,
                distanceTerre: 384400,
                composition1: "Oxygène",
                composition1Pourcent: 0.42,
                composition2: "Silicone",
                composition2Pourcent: 0.21,
                composition3: "Autre",
                composition3Pourcent: 0.37,
                satellites: "Aucun",
                temperature: 18,
                imagePrincipale: "Lune.image1",
                imageSecondaire: "Lune.image2",
                imageBigTile: "Lune.bigTile",
                imageLittleTile: "Lune.littleTile",
                texteDescription1: "La lune est un astre rocheux en orbite autour de la planète Terre. Elle n’a pas d’atmosphère et n’a ni eau liquide, ni végétation. Le 20 juillet 1969, elle fut explorée pour la première fois.",
                texteDescription2: "TextDescription2 Lorem ipsum",
                texteFact1: "texteFact1 Lorem ipsum",
                texteFact2: "texteFact2 Lorem ipsum",
                texteNews1: "texteNews1 Lorem ipsum",
                texteNews2: "texteNews2 Lorem ipsum",
                texteCourt: "Satellite terestre",
                                        index: 12),
Astre(name: "Proxima Centauri",
                chapitre : "Mars",
                nature: "Etoile",
                age: 4853000000,
                dateDecouverte: "21 Octobre 2022",
                sizeRayon: 107280,
                sizeCirconference: 0,
                distanceTerre: 40170000000,
                composition1: "N/A",
                composition1Pourcent: 0,
                composition2: "N/A",
                composition2Pourcent: 0,
                composition3: "N/A",
                composition3Pourcent: 0,
                satellites: "Aucun",
                temperature: 2768.85,
                imagePrincipale: "Proxima Centauri.image1",
                imageSecondaire: "Proxima Centauri.image2",
                imageBigTile: "Proxima Centauri.bigTile",
                imageLittleTile: "Proxima Centauri.littleTile",
                texteDescription1: "Alpha Centauri C (en abrégé α Cen C, parfois ACC), ou en français Alpha du Centaure C, est le système planétaire le plus proche du système solaire au sein de la Voie lactée. Il se situe à 4,244 années-lumière du Soleil (et donc de la Terre) dans la constellation du Centaure. C'est une des trois composantes qui forment le système Alpha Centauri avec le couple central Alpha Centauri A et B.",
                texteDescription2: "TextDescription2 Lorem ipsum",
                texteFact1: "texteFact1 Lorem ipsum",
                texteFact2: "texteFact2 Lorem ipsum",
                texteNews1: "texteNews1 Lorem ipsum",
                texteNews2: "texteNews2 Lorem ipsum",
                texteCourt: "L'étoile la plus proche",
                                        index: 13),
Astre(name: "Zeta Puppis",
                chapitre : "Mars",
                nature: "Etoile",
                age: 3202000,
                dateDecouverte: "01 Octobre 2022",
                sizeRayon: 9740000,
                sizeCirconference: 0,
                distanceTerre:10179746556000000,
                composition1: "N/A",
                composition1Pourcent: 0,
                composition2: "N/A",
                composition2Pourcent: 0,
                composition3: "N/A",
                composition3Pourcent: 0,
                satellites: "Aucun",
                temperature:41726.85,
                imagePrincipale: "Zeta Puppis.image1",
                imageSecondaire: "Zeta Puppis.image2",
                imageBigTile: "Zeta Puppis.bigTile",
                imageLittleTile: "Zeta Puppis.littleTile",
                texteDescription1: "C'est une supergéante bleue extrême, l'une des plus brillantes étoiles de la Voie lactée en termes de magnitude absolue. Visuellement, elle est 21 000 fois plus lumineuse que le Soleil ; cependant, étant une étoile bleue extrême, la plus grande partie de son rayonnement se situe dans l'ultraviolet, et quand cela est pris en compte, elle est environ 790 000 fois plus brillante que le Soleil (Lamers & Cassinelli 1999). Les étoiles bleues ne sont jamais très grandes et Naos ne fait pas exception, ayant seulement 20 fois le rayon du Soleil. Il revient aux supergéantes rouges comme Bételgeuse d'établir les records de taille.",
                texteDescription2: "TextDescription2 Lorem ipsum",
                texteFact1: "texteFact1 Lorem ipsum",
                texteFact2: "texteFact2 Lorem ipsum",
                texteNews1: "texteNews1 Lorem ipsum",
                texteNews2: "texteNews2 Lorem ipsum",
                texteCourt: "La géante bleu",
                                        index: 14),
Astre(name: "Antarès",
                chapitre : "Mars",
                nature: "Etoile",
                age: 11000000,
                dateDecouverte: "29 Septembre 2022",
                sizeRayon: 700000,
                sizeCirconference: 0,
                distanceTerre: 5203402050000000,
                composition1: "N/A",
                composition1Pourcent: 0,
                composition2: "N/A",
                composition2Pourcent: 0,
                composition3: "N/A",
                composition3Pourcent: 0,
                satellites: "Aucun",
                temperature: 3296.85,
                imagePrincipale: "Antarès.image1",
                imageSecondaire: "Antarès.image2",
                imageBigTile: "Antarès.bigTile",
                imageLittleTile: "Antarès.littleTile",
                texteDescription1: "Antarès est l’étoile la plus brillante de la constellation du Scorpion. Ayant épuisée toute sa reserve d’hydrogène, cette étoile arrive en fin de vie.",
                texteDescription2: "TextDescription2 Lorem ipsum",
                texteFact1: "texteFact1 Lorem ipsum",
                texteFact2: "texteFact2 Lorem ipsum",
                texteNews1: "texteNews1 Lorem ipsum",
                texteNews2: "texteNews2 Lorem ipsum",
                texteCourt: "La géante rouge",
                                        index: 15),
Astre(name: "SN 1054",
                chapitre : "Mars",
                nature: "Etoile",
                age: 0,
                dateDecouverte: "28 Septembre 2022",
                sizeRayon: 0,
                sizeCirconference: 0,
                distanceTerre: 47303655000000000,
                composition1: "N/A",
                composition1Pourcent: 0,
                composition2: "N/A",
                composition2Pourcent: 0,
                composition3: "N/A",
                composition3Pourcent: 0,
                satellites: "Aucun",
                temperature: 0,
                imagePrincipale: "SN 1054.image1",
                imageSecondaire: "SN 1054.image2",
                imageBigTile: "SN 1054.bigTile",
                imageLittleTile: "SN 1054.littleTile",
                texteDescription1: "La supernova de l'an 1054, ou, selon son appellation normalisée, SN 1054, est une supernova dont l'explosion a été observée à partir du mois de juillet 1054, pendant une durée d'environ deux ans. De nombreux documents du monde chinois relatent son observation, qui est également attestée par un document en provenance du monde arabe. En revanche, l'hypothèse formulée plus récemment de la connaissance et de la transcription de cet événement par des Européens et des Amérindiens de cette époque reste très incertaine.",
                texteDescription2: "TextDescription2 Lorem ipsum",
                texteFact1: "texteFact1 Lorem ipsum",
                texteFact2: "texteFact2 Lorem ipsum",
                texteNews1: "texteNews1 Lorem ipsum",
                texteNews2: "texteNews2 Lorem ipsum",
                texteCourt: "La première Supernova observée",
                                        index: 16),

Astre(name: "Titan",
                chapitre : "Saturne",
                nature: "Satellite",
                age: 4003000000,
                dateDecouverte: "18 Octobre 2022",
                sizeRayon: 25747,
                sizeCirconference: 16178,
                distanceTerre: 1500000000,
                composition1: "N/A",
                composition1Pourcent: 0,
                composition2: "N/A",
                composition2Pourcent: 0,
                composition3: "N/A",
                composition3Pourcent: 0,
                satellites: "Aucun",
                temperature: -179,
                imagePrincipale: "Titan.image1",
                imageSecondaire: "Titan.image2",
                imageBigTile: "Titan.bigTile",
                imageLittleTile: "Titan.littleTile",
                texteDescription1: "Titania, également appelé Uranus III, est le plus grand satellite naturel d'Uranus et le huitième par sa masse du Système solaire. Découvert par William Herschel en 1787, il doit son nom à Titania, la reine des fées de la pièce de Shakespeare, Le Songe d'une nuit d'été. Son orbite autour d'Uranus est entièrement située au sein de la magnétosphère de la planète.",
                texteDescription2: "TextDescription2 Lorem ipsum",
                texteFact1: "texteFact1 Lorem ipsum",
                texteFact2: "texteFact2 Lorem ipsum",
                texteNews1: "texteNews1 Lorem ipsum",
                texteNews2: "texteNews2 Lorem ipsum",
                texteCourt: "Satellite d'Uranus",
                                        index: 17),

Astre(name: "Europe",
                chapitre : "Jupiter",
                nature: "Satellite",
                age: 4503000000,
                dateDecouverte: "07 Octobre 2022",
                sizeRayon: 1560.8,
                sizeCirconference: 9807,
                distanceTerre: 628300000,
                composition1: "N/A",
                composition1Pourcent: 0,
                composition2: "N/A",
                composition2Pourcent: 0,
                composition3: "N/A",
                composition3Pourcent: 0,
                satellites: "Aucun",
                temperature: -183,
                imagePrincipale: "Europe.image1",
                imageSecondaire: "Europe.image2",
                imageBigTile: "Europe.bigTile",
                imageLittleTile: "Europe.littleTile",
                texteDescription1: "Europe est le 6ème satellite de Jupiter (sur 79 connues à ce jour). Il est légèrement plus petit que la Lune.",
                texteDescription2: "TextDescription2 Lorem ipsum",
                texteFact1: "texteFact1 Lorem ipsum",
                texteFact2: "texteFact2 Lorem ipsum",
                texteNews1: "texteNews1 Lorem ipsum",
                texteNews2: "texteNews2 Lorem ipsum",
                texteCourt: "La sixème lune de Jupiter",
                                        index: 18),
Astre(name: "Bob", chapitre : "",nature: "",age: 0,dateDecouverte: "",sizeRayon: 0,                sizeCirconference: 0,
                distanceTerre: 0,
                composition1: "N/A",
                composition1Pourcent: 0,
                composition2: "N/A",
                composition2Pourcent: 0,
                composition3: "N/A",
                composition3Pourcent: 0,
                satellites: "",
                temperature: 0,
                imagePrincipale: "",
                imageSecondaire: "",
                imageBigTile: "",
                imageLittleTile: "",
                texteDescription1: "Le signal émis depuis la ceinture d'astéroïdes revet une curieuse signature...",
                texteDescription2: "",
                texteFact1: "",
                texteFact2: "",
                texteNews1: "",
                texteNews2: "",
                texteCourt: "La ceinture d'astéroïdes",
                                        index: 19)
]
